export const FETCH_PUSH_TOOL_ACTIVITY_LIST = 'PUSHTOOL/FETCH/ACTIVITY/LIST'

export const FETCH_PUSH_TOOL_ACTIVITY_LIST_SUCCESS = 'PUSHTOOL/FETCH/ACTIVITY/LIST/SUCCESS'

export const FETCH_PUSH_TOOL_ACTIVITY_LIST_FAIL = 'PUSHTOOL/FETCH/ACTIVITY/LIST/FAIL'

export const FETCH_PUSH_TOOL_DETAIL = 'PUSHTOOL/FETCH/DETAIL'

export const FETCH_PUSH_TOOL_DETAIL_SUCCESS = 'PUSHTOOL/FETCH/DETAIL/SUCCESS'

export const FETCH_PUSH_TOOL_DETAIL_FAIL = 'PUSHTOOL/FETCH/DETAIL/FAIL'

export const SET_PUSH_TOOL_TAG_MODAL = 'PUSHTOOL/SET/TAG/MODAL'

export const SET_PUSH_TOOL_DOC_MODAL = 'PUSHTOOL/SET/DOC/MODAL'

export const SET_PUSH_TOOL_COUPON_MODAL = 'PUSHTOOL/SET/COUPON/MODAL'

export const SET_PUSH_TOOL_SELECTED_TAG = 'PUSHTOOL/SET/SELECTED/TAG'

export const SET_PUSH_TOOL_AUDIT_MODAL = 'PUSHTOOL/SET/AUDIT/MODAL'

export const SET_PUSH_TOOL_AUDIT_PARAMS = 'PUSHTOOL/SET/AUDIT/PARAMS'

export const SET_PUSH_TOOL_TASKLIST_PARAMS = 'PUSHTOOL/SET/TASKLIST/PARAMS'

export const SET_PUSH_TOOL_SELECTED_COUPON = 'PUSHTOOL/SET/SELECTED/COUPON'

export const SET_PUSH_TOOL_COUPON_SELECT_TYPE = 'PUSHTOOL/SET/COUPON/SELECT/TYPE'

export const SET_PUSH_TOOL_SEARCH_PARAMS = 'PUSHTOOL/SET/SEARCH/PARAMS'

export const FETCH_PUSH_TOOL_TEMPLATE_TAG = 'PUSHTOOL/FETCH/TEMPLATE/TAG'

export const FETCH_PUSH_TOOL_TEMPLATE_TAG_SUCCESS = 'PUSHTOOL/FETCH/TEMPLATE/TAG/SUCCESS'

export const FETCH_PUSH_TOOL_TEMPLATE_TAG_FAIL = 'PUSHTOOL/FETCH/TEMPLATE/TAG/FAIL'

export const SET_PUSH_TOOL_TEMPLATE_TAG = 'PUSHTOOL/SET/TEMPLATE/TAG'

export const SET_PUSH_TOOL_TEMPLATE_TAG_PRE = 'PUSHTOOL/SET/TEMPLATE/TAG/PRE'

export const FETCH_PUSH_TOOL_DETAIL_USER_TAG = 'PUSHTOOL/FETCH/DETAIL/USER/TAG'

export const FETCH_PUSH_TOOL_DETAIL_USER_TAG_SUCCESS = 'PUSHTOOL/FETCH/DETAIL/USER/TAG/SUCCESS'

export const FETCH_PUSH_TOOL_DETAIL_USER_TAG_FAIL = 'PUSHTOOL/FETCH/DETAIL/USER/TAG/FAIL'

export const FETCH_PUSH_TOOL_DETAIL_CHECK_PACKGE = 'FETCH/PUSH/TOOL/DETAIL/CHECK/PACKGE'

export const FETCH_PUSH_TOOL_DETAIL_CHECK_PACKGE_SUCCESS = 'FETCH/PUSH/TOOL/DETAIL/CHECK/PACKGE/SUCCESS'

export const FETCH_PUSH_TOOL_DETAIL_CHECK_PACKGE_FAIL = 'FETCH/PUSH/TOOL/DETAIL/CHECK/PACKGE/FAIL'

export const SET_PUSH_TOOL_CURRENT_PAGE_INDEX = 'PUSHTOOL/SET/CURRENT/PAGE/INDEX'

export const SET_PUSH_TOOL_PUSH_RULE = 'PUSHTOOL/SET/PUSH/RULE'

export const SET_PUSH_TOOL_ACTIVATED_TAB = 'PUSHTOOL/SET/ACTIVATED/TAB'

export const FETCH_PUSH_TOOL_COUPON_LIST = 'PUSHTOOL/FETCH/COUPON/LIST'

export const FETCH_PUSH_TOOL_COUPON_LIST_SUCCESS = 'PUSHTOOL/FETCH/COUPON/LIST/SUCCESS'

export const FETCH_PUSH_TOOL_COUPON_LIST_FAIL = 'PUSHTOOL/FETCH/COUPON/LIST/FAIL'

export const SET_PUSH_TOOL_COUPON_LIST_PARAMS = 'PUSHTOOL/SET/COUPON/LIST/PARAMS'

export const PUSH_TOOL_IS_XIAOJU_PUSH_CHECKED = 'PUSHTOOL/IS/XIAOJU/PUSH/CHECKED'

export const PUSH_SELECTED_BIZLINE_PARAMS = 'PUSH/SELECTED/BIZLINE/PARAMS'

export const FETCH_PUSH_GROUP_QUERY_LIST = 'FETCH/PUSH/GROUP/QUERY/LIST'

export const FETCH_PUSH_GROUP_QUERY_LIST_SUCCESS = 'FETCH/PUSH/GROUP/QUERY/LIST/SUCCESS'

export const FETCH_PUSH_GROUP_QUERY_LIST_FAIL = 'FETCH/PUSH/GROUP/QUERY/LIST/FAIL'

export const SET_PUSH_GROUP_CURRENT_PAGE_INDEX = 'SET/PUSH/GROUP/CURRENT/PAGE/INDEX'

export const SET_GROUP_QUERY_SEARCH_PARAMS = 'SET/GROUP/QUERY/SEARCH/PARAMS'

export const FETCH_PUSH_TOOL_DETAIL_ASYNC = 'FETCH/PUSH/TOOL/DETAIL/ASYNC'

export const SET_CREATE_EXPERIMENTMODAL_MODAL = 'SET/CREATE/EXPERIMENTMODAL/MODAL'

export const SET_PUSH_TOOL_EQUITY_MODAL = 'SET/PUSH/TOOL/EQUITY/MODAL'

export const FETCH_PUSH_EQUITY_LIST = 'FETCH/PUSH/EQUITY/LIST'
export const FETCH_PUSH_EQUITY_LIST_SUCCESS = 'FETCH/PUSH/EQUITY/LIST/SUCCESS'
export const FETCH_PUSH_EQUITY_LIST_FAIL = 'FETCH/PUSH/EQUITY/LIST/FAIL'
export const SAVE_EQUITY_DATA = 'SAVE/EQUITY/DATA'
export const SAVE_SELECT_ROWS = 'SAVE/SELECT/ROWS'
export const LOCKING_EQUITY_SELECTED = 'LOCKING/EQUITY/SELECTED'

