export const GET_METRIC_LIST_ASYNC = 'GET/METRIC/LIST/ASYNC'
export const GET_METRIC_LIST = 'GET/METRIC/LIST'
export const GET_METRIC_LIST_SUCCESS = 'GET/METRIC/LIST/SUCCESS'
export const GET_METRIC_LIST_FAIL = 'GET/METRIC/LIST/FAIL'

export const GET_CATEGORY_LIST_ASYNC = 'GET/CATEGORY/LIST/ASYNC'
export const GET_CATEGORY_LIST = 'GET/CATEGORY/LIST'
export const GET_CATEGORY_LIST_SUCCESS = 'GET/CATEGORY/LIST/SUCCESS'
export const GET_CATEGORY_LIST_FAIL = 'GET/CATEGORY/LIST/FAIL'

export const FETCH_USER_TAG_INQUIRE_ASYNC = 'FETCH/USER/TAG/INQUIRE/ASYNC'
export const FETCH_USER_TAG_INQUIRE = 'FETCH/USER/TAG/INQUIRE'
export const FETCH_USER_TAG_INQUIRE_SUCCESS = 'FETCH/USER/TAG/INQUIRE/SUCCESS'
export const FETCH_USER_TAG_INQUIRE_FAIL = 'FETCH/USER/TAG/INQUIRE/FAIL'



export const FETCH_USER_TAG_CATEGORY = 'FETCH/USER/TAG/CATEGORY'
export const FETCH_USER_TAG_CATEGORY_SUCCESS = 'FETCH/USER/TAG/CATEGORY/SUCCESS'
export const FETCH_USER_TAG_CATEGORY_FAIL = 'FETCH/USER/TAG/CATEGORY/FAIL'
export const FETCH_USER_TAG_CLEAR_CATEGORY = 'FETCH/USER/TAG/CLEAR/CATEGORY'
export const GET_METRIC_DETAIL_ASYNC = 'GET/METRIC/DETAIL/ASYNC'
export const GET_METRIC_DETAIL = 'GET/METRIC/DETAIL'
export const GET_MATRIC_EDTAIL_SUCCESS = 'GET/METRIC/DETAIL/SUCCESS'
export const SELECT_USER_TAG_CATEGORY_ITEM = 'SELECT/USER/TAG/CATEGORY/ITEM'

export const GET_METRIC_DETAIL_FAIL = 'GET/METRIC/DETAIL/FAIL'
export const FETCH_CATEGORY_GET_DETAIL = 'FETCH/CATEGORY/GET/DETAIL'
export const FETCH_CATEGORY_GET_DETAIL_SUCCESS = 'FETCH/CATEGORY/GET/DETAIL/SUCCESS'
export const FETCH_CATEGORY_GET_DETAIL_FAIL = 'FETCH/CATEGORY/GET/DETAIL/FAIL'
